### ISSUE TITLE
Update "About Tool" UI

### ISSUE THREAD

**Issue by ajlevitz** [azilc/polling-place-map#14]
I'd like the text size of the header to be smaller, for the body text to be be the size of the analytics FYI, and for there to be one more line break above it.

**Comment by rmx90210** [comment]
The analytics disclaimer text is pretty small, since it's not essential reading. Just wondering if this has an impact on accessibility?

**Comment by ajlevitz** [comment]
I see the "about" as non-essential reading, as well. It's way too big a block of text to expect people to see it. Though with that said, it'd probably be more helpful to lead with "This is not a voter registration tool."
