### ISSUE TITLE
Copy Changes [AJL]

### ISSUE THREAD

**Issue by ajlevitz** [azilc/polling-place-map#15]
Update text: 

**Early Voting**
Early voting runs until 5PM Friday, October 30. Dates and hours vary by location. Voter identification is required to vote in person. More information <here \| https://azsos.gov/elections/voting-election>. <hr>At these locations, you can also drop off the ballot you received by mail. Look at Emergency Voting locations for voting options from 5PM Friday, October 30, to 5PM Monday, November 2.

**Drop Boxes**
If you have received a ballot by mail, you can use any drop box in the county of your voter registration until 7PM Tuesday, November 3 (Election Day). If you cannot mail your ballot back by October 27, it is recommended that you drop it off.<hr>In addition to the options below, all voting locations when open will accept the ballot you received by mail. Early Voting Locations will show options until 5PM Friday, October 30. Emergency Voting Locations will show options from 5PM Friday, October 30 to 5PM Monday, November 2. Election Day Voting Locations are all open from 6AM - 7PM on Tuesday, November 3.

**Emergency Voting**
Emergency Voting is available from 5PM Friday, October 30 to 5PM Monday, November. It is for those who are unable to vote early or on Election day. Dates and hours vary by location. Voter identification is required to vote in person. More information <here \| https://azsos.gov/elections/voting-election>.<hr>At these locations, you can also drop off the ballot you received by mail.

**Election Day voting**
All Election Day Voting Locations will be open from 6AM to 7PM on Tuesday, November 3. As long as you are in line before 7:00 PM, you will still be able to vote. Voter identification is required to vote in person. More information <here \| https://azsos.gov/elections/voting-election>. <hr>At these locations, you can also drop off the ballot you received by mail.

**Comment by ajlevitz** [comment]
I don't actually have an environment right now to test JS updates, and so I'm not sure whether the <hr>s will work inside v-html the way I am hoping. @rbrtmrtn , if you can let me know how to do <hr> within the v-html variable, I can do this pull request. Otherwise, the text I want is above (it got lengthy, hence taking Nick's idea of the HR).

I think this looks okay? Though it moves results SO FAR down the page. 
![Screen Shot 2020-10-26 at 9 13 50 PM](https://user-images.githubusercontent.com/4675053/97257569-8dd4bd80-17d3-11eb-827e-647ee0e4a382.png)

**Comment by rmx90210** [comment]
Hey @ajlevitz ! You should be able to do an `<hr />` right in that `v-html="..."` value. Were those included in PR #24 ? Everything looked OK to me!

**Comment by ajlevitz** [comment]
I didn't include those in that PR, no. I'll create a new one now!

**Comment by ajlevitz** [comment]
https://docs.google.com/document/d/1YmVQ2BRDpGiqg9fuzUVADXVsMV0OE-8HFbWBKJz1rA0/edit#heading=h.7beg2dq5urqz
