### ISSUE TITLE
Mapbox search: change ghost text

### ISSUE THREAD

**Issue by ajlevitz** [azilc/polling-place-map#17]
Right now, it just says "Search". Many of the places someone might try to input are not actually in the Mapbox database, so we want to encourage them to type something that would be successful.

"Search for a nearby town"

**Comment by rmx90210** [comment]
When creating the geocoder it should take a parameter `placeholder` that lets you do this.

**Comment by elizzard** [comment]
Ah @ajlevitz sorry, I tunneled. This is what it looks like:
<img width="916" alt="Screen Shot 2020-10-28 at 10 53 35 PM" src="https://user-images.githubusercontent.com/5553491/97531219-f86f3000-1970-11eb-9199-db95812395de.png">
<img width="466" alt="Screen Shot 2020-10-28 at 10 54 07 PM" src="https://user-images.githubusercontent.com/5553491/97531229-fc9b4d80-1970-11eb-9059-22925177b248.png">
